channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=26.0.1
- pip:
  - mlflow==3.10.1
  - cloudpickle==3.1.2
  - dill==0.4.1
  - numpy==1.26.0
  - pandas==2.3.3
  - torch==2.10.0
  - tqdm==4.67.3
name: mlflow-env
